#Homework 2 Trivial Pursuit
#Mindy Mohr
print("ART AND LITERATURE: Who painted Starry Night?")
print("a. Vincent van Gogh")
print("b. Michelangelo")
print("c. Leonardo da Vinci")
choice=input("Enter your choice:")
if choice == "a": print("Correct!")
if choice != "a": print("The correct answer was a")
print("ENTERTAINMENT: How many oscars did Alfred Hitchcock win?")
print("a. None")
print("b. One")
print("c. Two")
choice=input("Enter your choice:")
if choice == "a": print("Correct!")
if choice != "a": print("The correct answer was a")
print("GEOGRAPHY: Which is the largest ocean?")
print("a. Pacific")
print("b. Atlantic")
print("c. Indian")
choice=input("Enter your choice:")
if choice == "a": print("Correct!")
if choice != "a": print("The correct answer was a")
print("HISTORY: Who was the first U.S. president to appear on a coin?")
print("a. Washington")
print("b. Lincoln")
print("c. Jefferson")
choice=input("Enter your choice:")
if choice == "b": print("Correct!")
if choice != "b": print("The correct answer was b")
print("SCIENCE AND NATURE: Can pigs swim?")
print("a. Yes")
print("b. No")
print("c. Only in salt water")
choice=input("Enter your choice:")
if choice == "a": print("Correct!")
if choice != "a": print("The correct answer was a")
print("SPORT AND LEISURE: What color is the middle Olympic ring?")
print("a. Red")
print("b. Blue")
print("c. Black")
choice=input("Enter your choice:")
if choice == "c": print("Correct!")
if choice != "c": print("The correct answer was c")
